# Generated by Django 5.2 on 2026-09-08 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_weeklyprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectproposal',
            options={},
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='guide',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'GUIDE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guided_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='abstract',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='domain',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='domain_expert',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'EXPERT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('EXPERT_ASSIGNED', 'Expert Assigned'), ('EXPERT_APPROVED', 'Expert Approved'), ('COORDINATOR_APPROVED', 'Coordinator Approved'), ('GUIDE_ASSIGNED', 'Guide Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='SUBMITTED', max_length=30),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='technologies',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='WeeklyProgress',
        ),
    ]
