# Generated by Django 6.0.7 on 2026-09-10 06:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_projectproposal_status_projectprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectproposal',
            name='expert_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='projectprogress',
            constraint=models.UniqueConstraint(fields=('project', 'week_number'), name='unique_project_week_progress'),
        ),
    ]
