# Generated by Django 5.2 on 2026-09-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectproposal_expert_comments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectprogress',
            options={'ordering': ['-week_number', '-submitted_at']},
        ),
        migrations.RemoveField(
            model_name='projectproposal',
            name='expert_comments',
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('EXPERT_ASSIGNED', 'Expert Assigned'), ('CHANGES_REQUESTED', 'Changes Requested'), ('EXPERT_APPROVED', 'Expert Approved'), ('COORDINATOR_APPROVED', 'Coordinator Approved'), ('GUIDE_ASSIGNED', 'Guide Assigned'), ('GUIDE_REJECTED', 'Guide Rejected'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='SUBMITTED', max_length=30),
        ),
    ]
