# Generated by Django 5.2 on 2026-09-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_projectprogress_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectproposal',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('EXPERT_ASSIGNED', 'Expert Assigned'), ('CHANGES_REQUESTED', 'Changes Requested'), ('CHANGES_SENT_TO_STUDENT', 'Changes Sent To Student'), ('EXPERT_APPROVED', 'Expert Approved'), ('COORDINATOR_APPROVED', 'Coordinator Approved'), ('GUIDE_ASSIGNED', 'Guide Assigned'), ('GUIDE_REJECTED', 'Guide Rejected'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=30),
        ),
    ]
