# Generated by Django 5.2 on 2026-09-14 04:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_projectproposal_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectprogress',
            options={'ordering': ['submitted_at']},
        ),
        migrations.RemoveConstraint(
            model_name='projectprogress',
            name='unique_project_week_progress',
        ),
        migrations.RemoveField(
            model_name='projectprogress',
            name='week_number',
        ),
        migrations.AddField(
            model_name='projectprogress',
            name='report_type',
            field=models.CharField(choices=[('PROGRESS_1', 'Progress Report 1'), ('PROGRESS_2', 'Progress Report 2'), ('PROGRESS_3', 'Progress Report 3'), ('FINAL_REPORT', 'Final Report')], default='exit', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('EXPERT_ASSIGNED', 'Expert Assigned'), ('CHANGES_REQUESTED', 'Changes Requested'), ('CHANGES_SENT_TO_STUDENT', 'Changes Sent To Student'), ('EXPERT_APPROVED', 'Expert Approved'), ('COORDINATOR_APPROVED', 'Coordinator Approved'), ('GUIDE_ASSIGNED', 'Guide Assigned'), ('GUIDE_REJECTED', 'Guide Rejected'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=40),
        ),
        migrations.AddConstraint(
            model_name='projectprogress',
            constraint=models.UniqueConstraint(fields=('project', 'report_type'), name='unique_project_report_type'),
        ),
    ]
