# Generated by Django 5.2 on 2026-09-14 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_projectprogress_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='projectprogress',
            name='unique_project_report_type',
        ),
        migrations.RenameField(
            model_name='proposalchangerequest',
            old_name='message',
            new_name='comments',
        ),
        migrations.RemoveField(
            model_name='proposalchangerequest',
            name='coordinator',
        ),
        migrations.RemoveField(
            model_name='proposalchangerequest',
            name='resubmitted_at',
        ),
        migrations.RemoveField(
            model_name='proposalchangerequest',
            name='sent_to_student_at',
        ),
        migrations.AddField(
            model_name='proposalchangerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='projectprogress',
            name='report_type',
            field=models.CharField(choices=[('WEEKLY_PROGRESS', 'Weekly Progress'), ('FINAL_REPORT', 'Final Report')], max_length=30),
        ),
        migrations.AlterField(
            model_name='proposalchangerequest',
            name='expert',
            field=models.ForeignKey(limit_choices_to={'role': 'EXPERT'}, on_delete=django.db.models.deletion.CASCADE, related_name='proposal_change_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposalchangerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT_TO_STUDENT', 'Sent To Student'), ('RESUBMITTED', 'Resubmitted'), ('CLOSED', 'Closed')], default='PENDING', max_length=30),
        ),
    ]
