# Generated by Django 6.0.7 on 2026-09-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_projectprogress_unique_project_report_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectproposal',
            name='project_type',
            field=models.CharField(choices=[('MINI', 'Mini Project'), ('MAIN', 'Main Project')], default='MAIN', max_length=10),
        ),
    ]
