# Generated by Django 5.2.8 on 2026-09-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_projectproposal_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectprogress',
            name='report_type',
            field=models.CharField(choices=[('WEEKLY_PROGRESS', 'Weekly Progress Report'), ('FINAL_REPORT', 'Final Report')], max_length=30),
        ),
    ]
