# Generated by Django 5.2 on 2026-09-24 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_projectprogress_report_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectprogress',
            name='student',
            field=models.ForeignKey(limit_choices_to={'is_student': True}, on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='domain_expert',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_expert': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='guide',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_guide': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guided_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='student',
            field=models.ForeignKey(limit_choices_to={'is_student': True}, on_delete=django.db.models.deletion.CASCADE, related_name='project_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposalchangerequest',
            name='expert',
            field=models.ForeignKey(limit_choices_to={'is_expert': True}, on_delete=django.db.models.deletion.CASCADE, related_name='proposal_change_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
