# Generated by Django 5.2 on 2026-09-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_projectprogress_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalchangerequest',
            name='coordinator_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
