# Generated by Django 5.2 on 2026-09-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_proposalchangerequest_coordinator_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectprogress',
            name='report_type',
            field=models.CharField(choices=[('PROGRESS_1', 'Progress Report 1'), ('PROGRESS_2', 'Progress Report 2'), ('PROGRESS_3', 'Progress Report 3'), ('FINAL_REPORT', 'Final Report')], max_length=30),
        ),
    ]
