# Generated by Django 5.2 on 2026-10-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_projectmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectproposal',
            name='review_date',
            field=models.DateTimeField(blank=True, help_text='Scheduled date and time for the project review by the panel.', null=True),
        ),
    ]
