# Generated by Django 5.2 on 2026-10-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_projectproposal_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectproposal',
            name='review_document',
            field=models.FileField(blank=True, help_text='Optional document attached by coordinator for the review.', null=True, upload_to='review_documents/'),
        ),
    ]
