# Generated by Django 5.2 on 2026-10-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_projectproposal_review_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectproposal',
            name='review_document',
        ),
        migrations.AddField(
            model_name='projectprogress',
            name='marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
