# Generated by Django 5.2 on 2026-10-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_remove_projectproposal_review_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprogress',
            name='detailed_marks',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
