# Generated by Django 5.2.8 on 2026-10-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_projectprogress_detailed_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprogress',
            name='week_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
