# Generated by Django 6.0.7 on 2026-09-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guideevaluation',
            old_name='evaluated_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='guideevaluation',
            name='feedback',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
