# Generated by Django 5.2 on 2026-09-24 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_rename_evaluated_at_guideevaluation_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideevaluation',
            name='guide',
            field=models.ForeignKey(limit_choices_to={'is_guide': True}, on_delete=django.db.models.deletion.CASCADE, related_name='guide_evaluations', to=settings.AUTH_USER_MODEL),
        ),
    ]
