# Generated by Django 5.2 on 2026-10-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0003_alter_guideevaluation_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideevaluation',
            name='detailed_marks',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
