# Generated by Django 5.2 on 2026-09-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_batch_alter_user_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('COORDINATOR', 'Coordinator'), ('EXPERT', 'Domain Expert'), ('GUIDE', 'Guide'), ('PANEL', 'Panel Member')], default='STUDENT', max_length=20),
        ),
    ]
