# Generated by Django 5.2 on 2026-09-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='domain_of_expertise',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
