# Generated by Django 5.2 on 2026-10-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_faculty",
            field=models.BooleanField(default=False),
        ),
    ]
